# determine variables after configuring the environment (reusing gears)

# Rules for per-OS installers need to reference MODULE variables, but BROWSER
#   is not defined.  So explicitly define all module vars, instead of using:
#   $(BROWSER)_MODULE_DLL = $($(BROWSER)_OUTDIR)/$(DLL_PREFIX)$(MODULE)$(DLL_SUFFIX)
FF2_MODULE_DLL      = $(FF2_OUTDIR)/$(DLL_PREFIX)$(MODULE)$(DLL_SUFFIX)
FF3_MODULE_DLL      = $(FF3_OUTDIR)/$(DLL_PREFIX)$(MODULE)$(DLL_SUFFIX)
FF31_MODULE_DLL     = $(FF31_OUTDIR)/$(DLL_PREFIX)$(MODULE)$(DLL_SUFFIX)
FF36_MODULE_DLL     = $(FF36_OUTDIR)/$(DLL_PREFIX)$(MODULE)$(DLL_SUFFIX)
IE_MODULE_DLL       = $(IE_OUTDIR)/$(DLL_PREFIX)$(MODULE)$(DLL_SUFFIX)
IEMOBILE_MODULE_DLL = $(IEMOBILE_OUTDIR)/$(DLL_PREFIX)$(MODULE)$(DLL_SUFFIX)
NPAPI_MODULE_DLL    = $(NPAPI_OUTDIR)/$(DLL_PREFIX)$(MODULE)$(DLL_SUFFIX)
# We have to use different names for the IE Mobile and Opera Mobile DLLs on
# WinCE to prevent clashes.
OPERA_MODULE_DLL    = $(OPERA_OUTDIR)/$(DLL_PREFIX)$(MODULE)op$(DLL_SUFFIX)
SF_MODULE_DLL       = $(SF_OUTDIR)/$(DLL_PREFIX)$(MODULE)$(DLL_SUFFIX)

FF36_MODULE_TYPELIB     = $(FF36_OUTDIR)/$(MODULE).xpt
IEMOBILE_WINCESETUP_DLL = $(IEMOBILE_OUTDIR)/$(DLL_PREFIX)setup$(DLL_SUFFIX)
OPERA_WINCESETUP_DLL    = $(OPERA_OUTDIR)/$(DLL_PREFIX)setup$(DLL_SUFFIX)
SF_INPUTMANAGER_EXE     = $(SF_OUTDIR)/$(EXE_PREFIX)GearsEnabler$(EXE_SUFFIX)

INSTALLERS_OUTDIR = $(OUTDIR)/installers

ifeq ($(OS),linux)
# On Linux, we distinguish between the 64-bit and default (32-bit) installers.
ifeq ($(ARCH),x86_64)
INSTALLER_BASE_NAME = $(MODULE)-$(OS)-$(ARCH)-$(MODE)-$(VERSION)
else
INSTALLER_BASE_NAME = $(MODULE)-$(OS)-$(MODE)-$(VERSION)
endif
else
# On OSes other than Linux, there is no ARCH in INSTALLER_BASE_NAME because
# we created merged installers.
INSTALLER_BASE_NAME = $(MODULE)-$(OS)-$(MODE)-$(VERSION)
endif

SF_INSTALLER_PLUGIN_BUNDLE = $(INSTALLERS_OUTDIR)/Safari/StatsPane.bundle
SF_PLUGIN_BUNDLE           = $(INSTALLERS_OUTDIR)/Safari/Gears.bundle
SF_PLUGIN_PROXY_BUNDLE     = $(INSTALLERS_OUTDIR)/Safari/Gears.plugin
SF_INPUTMANAGER_BUNDLE     = $(INSTALLERS_OUTDIR)/Safari/GearsEnabler
SF_INSTALLER_PKG       = $(INSTALLERS_OUTDIR)/Safari/Gears.pkg
FFMERGED_INSTALLER_XPI = $(INSTALLERS_OUTDIR)/$(INSTALLER_BASE_NAME).xpi
NPAPI_INSTALLER_MSI    = $(INSTALLERS_OUTDIR)/$(INSTALLER_BASE_NAME)-chrome.msi
WIN32_INSTALLER_MSI    = $(INSTALLERS_OUTDIR)/$(INSTALLER_BASE_NAME).msi
IEMOBILE_WINCE_INSTALLER_CAB = $(INSTALLERS_OUTDIR)/$(INSTALLER_BASE_NAME).cab
OPERA_WINCE_INSTALLER_CAB    = $(INSTALLERS_OUTDIR)/$(INSTALLER_BASE_NAME)-opera.cab
INFSRC_BASE_NAME = wince_cab
IEMOBILE_INFSRC = $(COMMON_OUTDIR)/genfiles/$(INFSRC_BASE_NAME)_iemobile.inf
OPERA_INFSRC    = $(COMMON_OUTDIR)/genfiles/$(INFSRC_BASE_NAME)_op.inf
SYMBIAN_INSTALLER_SISX = $(INSTALLERS_OUTDIR)/$(INSTALLER_BASE_NAME).sisx
