HAS_WIFI = 0
HAS_UI = 1

CPPFLAGS += -DWITH_JVMTI=1
CPPFLAGS += -DWITH_JVMTI_MEMORY=1

CPPFLAGS += -DVAR_OBJECT_SIZE=1
#CPPFLAGS += -DVAR_SCREEN_DATA=1
CPPFLAGS += -DVAR_MEMORY_DATA=1
CPPFLAGS += -DVAR_TIME_DATA=1
CPPFLAGS += -DVAR_LOAD_DATA=1
CPPFLAGS += -DVAR_PROCESSOR_DATA=1
#CPPFLAGS += -DVAR_VOLUME_DATA=1
#CPPFLAGS += -DVAR_NETWORK_DATA=1
#CPPFLAGS += -DVAR_ENERGY_DATA=1
CPPFLAGS += -DVAR_IO_DATA=1
CPPFLAGS += -DVAR_ARBITRARY_PROCESS_DATA=1
CPPFLAGS += -DVAR_CURRENT_PROCESS_DATA=1
CPPFLAGS += -DVAR_ALL_PROCESSES_DATA=1
#CPPFLAGS += -DVAR_DEBUG=1
